# Generated by Django 5.0.6 on 2024-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Статус платежа'),
        ),
    ]
